services:
  app_backend:
    build: .
    container_name: go_backend_mouse
    restart: always
    ports:
      - "54300:${PORT:-3000}" # Asegúrate de que coincida con PORT en tu .env (o cámbialo a "3000:3000")
    environment:
      - ENV=${ENV:-development}
      - PORT=${PORT:-3000}
      # Base de datos SQLite (Ruta interna del contenedor para persistencia)
      - DB_PATH=/app/data/app.db
      # Autenticación
      - JWT_SECRETO=${JWT_SECRETO}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - JWT_TIEMPO_EXPIRA=${JWT_TIEMPO_EXPIRA:-3600}
    volumes:
      # Montamos un volumen para que la base de datos SQLite no se borre al reiniciar el contenedor
      - sqlite_data:/app/data
    networks:
      - docker_app_network

# Eliminamos los volúmenes de redis y postgres
volumes:
  sqlite_data:
    driver: local

# La red se mantiene por si en el futuro agregas un proxy inverso (como Nginx o Traefik)
networks:
  docker_app_network:
    driver: bridge
